include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Performance & Const Usage
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_redundant_argument_values: true

    # Code Consistency
    avoid_print: true
    prefer_single_quotes: true
    always_use_package_imports: true
    # Allow relative imports within the same package
    avoid_relative_lib_imports: false

    # Style & Readability
    sort_child_properties_last: true
    require_trailing_commas: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    unnecessary_this: true
    prefer_is_empty: true
    prefer_is_not_empty: true

    # Safety
    prefer_null_aware_operators: true
    use_build_context_synchronously: true
    avoid_types_as_parameter_names: true
    avoid_dynamic_calls: true

    # Best Practices
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
  errors:
    invalid_annotation_target: ignore
    avoid_dynamic_calls: error
    deprecated_member_use: error
    use_build_context_synchronously: error
    avoid_print: error

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

